wandb_version: 1

all_latents:
  value: true
batch-size:
  value: 256
beta:
  value: 1
dataset_size:
  value: 1000
epochs:
  value: 10
lr:
  value: 0.01
name:
  value: test
sample_size:
  value: 64
seed:
  value: 9321
